### ISSUE TITLE
工期について

### ISSUE THREAD

**Issue by nagasawajun** [soja-suidou/shisetu_kanri_tenken#12]
本業務、なかなか進んでおらず申し訳ございません。
工期を見直すとR5/9/19となっておりました。
今後の進め方についてご相談させていただきたいのですが、本日ご不在でしたので、来週月曜日にお電話させていただいてもよろしいでしょうか。
どうぞよろしくお願いいたします。

**Comment by yamamoto-ryuzo** [comment]
10月からの業務で利用するので工期の延期は、なかなか難しいです。
どの程度までできるか、工程をください。
以上。

**Comment by nagasawajun** [comment]
直前にバタバタと申し訳ございません。
9月中には稼働可能となるスケジュールを検討いたしました。ご確認お願いいたします。
2点日程調整をさせていただきたいのですが、
・10月以降に利用するであろうメンテナンス台帳等に関しても事前にある程度検討しておきたいのですが、10月以降の運用方針をヒアリングさせていただけないでしょうか。
エコニティさんも同席したいのでZOOMでお願いいたします。
日程は9/14の夕方くらいではご都合いかがでしょうか。
・データ格納後のシステムで操作説明をする予定なのですが、日程について、
　第一希望：9/27終日
　第二希望：9/29終日
　第三希望：9/25終日
　でご都合のつく日はございますでしょうか。
　
\\soja\総社市\水道施設管理点検システム導入業務
工期（案）.xlsx

**Comment by yamamoto-ryuzo** [comment]
すいません。
操作説明は仕様書に入っていないので、サービス的なものと考えております。

出来れば、初期運用を行って、市と施設管理の受託業者がある程度使った後に、必要であればお願いいたします。
わかりやすいシステムなので、すでにいただいているサポート用の掲示板で事足りるような気もします。
急ぐのは仕様書内の初期設定のみです。
工期（案）.xlsxは後程確認し、また、ご連絡いたします。

**Comment by yamamoto-ryuzo** [comment]
>・10月以降に利用するであろうメンテナンス台帳等に関しても事前にある程度検討しておきたいのですが、10月以降の運用方針をヒアリングさせていただけないでしょうか。

　メインテナンス台帳等の他の機能についても、仕様書外です。
　そもそも移行する明確なデータがなく、こちらの「データロガーから作成したマスターデータ候補」のみです。
　初期設定はある程度標準的なものを提示していただければ、こちらの「マスターデータ候補」と突合して、おしまい程度です。
　どちらかというと、業務の本筋は
　
　　（５）システムへのデータ設定　　　　　　　　　　　５人
　　　・「設備管理の匠WEB版」への情報移行
　　　
　ですので。
　なので、それ、必要に応じて別発注か変更対象の内容となります。

**Comment by nagasawajun** [comment]
ありがとうございます。

（５）システムへのデータ設定　　　　　　　　　　　５人
　　　・「設備管理の匠WEB版」への情報移行
を急ぎます。

**Comment by soja-suidou** [comment]
@nagasawajun 
今更ですが、工期ですが　匠の費用を年度末まで支払いしていただいている時点でR6.3.31でした。
バタバタして指示が遅れていますが、変更と工期延期を同時に行うので、引き続きよろしくお願いいたします。

1.固定資産台帳に関するもの
　必要に応じて、変更対応とするか別途契約とします。

2.保守に関するもの
　状況を見ながら、このサイトへの　総社市独自にマニュアル追加を含めて検討しております。
　　　　特に、ルール的なものを取りまとめてもらう必要があると思います。
　現在、とりあえず、緊急対応業務に関する最低限のものをマニュアル化しております、今しばらくお待ちください。

工期について、問題なければクローズしてください。

**Comment by nagasawajun** [comment]
R6.3.31について、承知いたしました。
