### ISSUE TITLE
茅野様：操作研修について

### ISSUE THREAD

**Issue by nagasawajun** [soja-suidou/shisetu_kanri_tenken#13]
茅野様
ご依頼いただいた設備管理の匠の操作研修について、9/27はどうしても空けられないため、
9/29（金）15：00～
お願いできますでしょうか。
ZOOMですので、点検業者様も社内から参加していただくことが可能です。

どうぞよろしくお願いいたします。

**Comment by soja-suidou** [comment]
お世話になります。茅野です。
操作研修ですが、９月２９日（金）午後３時からで OK です。

日圧さん、上水道課（多分２名くらい）で参加します。
アイサポートさんは zoom 参加ですか？こちらへ来られますか？

**Comment by yamamoto-ryuzo** [comment]
>操作研修ですが、９月２９日（金）午後３時から

茅野さんへ
　私も参加希望！
　スケジュール入れておいて！

**Comment by soja-suidou** [comment]
課長、了解です。スケジュールへ登録しておきます。

**Comment by nagasawajun** [comment]
茅野様
返信ありがとうございます。
WEB会議の機器を総社市様でご準備可能であれば、弊社もZOOM参加とさせていただこうと思います。
どうぞよろしくお願いいたします。
ZOOMIDなどは追ってご連絡いたします。

**Comment by yamamoto-ryuzo** [comment]
>WEB会議の機器を総社市様でご準備可能

茅野さんへ
　清音出張所の電波環境極悪で，回線不良になりやすいので，市の回線でよろしく！
　こないだの日水コンの二の前になると説明会にならない。
　今回画面共有なかったら意味ナッシングの会議になるので。

**Comment by soja-suidou** [comment]
> WEB会議の機器を総社市様でご準備可能であれば、弊社もZOOM参加とさせていただこうと思います。
上水道課で zoom 端末の準備をします。準備ができましたらＩＤ等ご連絡ください。
なお、スクリーンではなく数人でノートパソコンの画面を見るかたちになります。

> 清音出張所の電波環境極悪で，回線不良になりやすいので，市の回線でよろしく！
了解しました。

では皆様、金曜日よろしくお願いします。。

**Comment by nagasawajun** [comment]
山本課長
\\Soja\総社市\水道施設管理点検システム導入業務\02システム等の導入に関する諸事務\05ユーザ管理
ここにユーザ情報を保存しております。

**Comment by nagasawajun** [comment]
Microsoft Teams になりました。
アカウントをお持ちでなくても参加できると思います。
15時よりどうぞよろしくお願いいたします。

Microsoft Teams ミーティング 
コンピュータ、モバイルアプリケーション、またはルームデバイスで参加する 
[ここをクリックして会議に参加してください](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZDE0ZjUzNzctZTllMS00NDFlLTk2MDktYWRiZGQ2MzRiN2M5%40thread.v2/0?context=%7b%22Tid%22%3a%220db95585-1fd0-4a5f-9a4e-0ab5679e89a5%22%2c%22Oid%22%3a%2284ec1ffc-f86c-4a08-84a2-149f956a791b%22%7d) 
会議 ID: 437 088 500 199 
パスコード: Msehxm 
[Teams のダウンロード](https://www.microsoft.com/en-us/microsoft-teams/download-app) | [Web に参加](https://www.microsoft.com/microsoft-teams/join-a-meeting)
[詳細情報ヘルプ](https://aka.ms/JoinTeamsMeeting) | [会議のオプション](https://teams.microsoft.com/meetingOptions/?organizerId=84ec1ffc-f86c-4a08-84a2-149f956a791b&tenantId=0db95585-1fd0-4a5f-9a4e-0ab5679e89a5&threadId=19_meeting_ZDE0ZjUzNzctZTllMS00NDFlLTk2MDktYWRiZGQ2MzRiN2M5@thread.v2&messageId=0&language=ja-JP) 
________________________________________________________________________________
