### ISSUE TITLE
スマホアプリからのアクセスについて

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [soja-suidou/shisetu_kanri_tenken#14]
スマホ端末からのアクセスに専用　組織ID　が必要となっております。
たぶん，WEB版にはアクセス権があるのかと思います。
利用の権限有無を含めて確認ください。
以下ライセンスのページ
「設備管理の匠」はデータベース毎にライセンス課金されます。1つのデータベースに対して利用する人数の制約は基本的にはありません。つまり、データベースを、ネットワークを通じて複数のパソコン（WEB版の場合タブレットPC、スマートフォンを含む）でご利用いただいても、価格は変わらないということになります。
なお、標準版・SQLサーバ版は各パソコンには実行ファイルをそれぞれセットアップする必要があります」

**Comment by nagasawajun** [comment]
お電話ありがとうございました。スマホアプリについて、エコニティに確認取れましたら再度返信いたします。

**Comment by nagasawajun** [comment]
サーバURLは
[https://soja-suido.net//](https://soja-suido.net/)

組織IDは
2292a44d-e7d8-4321-801c-09b1d5f10cf0

でした。取り急ぎご報告いたします。
点検グループを選ぶとか出てきましたので、対応を調べます。

**Comment by soja-suidou** [comment]
>点検グループを選ぶとか出てきましたので、対応を調べます。

それ、今回の業務外なのでとりあえずOKです。
必要に応じてそのたもろもろの委託を別途もしくは変更で行うと思います。
説明会次第かもでしょうか？ちなみに、出席予定でしたが、私は別の会議が入っていて出席できませんが、よろしくお願いします。
