### ISSUE TITLE
旧施設台帳について　情報を追加しました。

### ISSUE THREAD

**Issue by soja-suidou** [soja-suidou/shisetu_kanri_tenken#17]
@koyamayutaka930 
旧施設台帳について　情報を追加しました。
確認の上、回答ください。
https://github.com/soja-suidou/shisetu_kanri_tenken/blob/main/%E5%8C%A0%E8%A8%AD%E5%AE%9A%E6%83%85%E5%A0%B1%EF%BC%88%E6%96%BD%E8%A8%AD%E5%8F%B0%E5%B8%B3%EF%BC%89/%E6%97%A7%E6%96%BD%E8%A8%AD%E5%8F%B0%E5%B8%B3.md

**Comment by koyamayutaka930** [comment]
確認致しました。

**Comment by soja-suidou** [comment]
@koyamayutaka930 
OPENしたものがCLOSEなので今後は気を付けてください。
簡単なものでもそうしていないと量が増えるとわからなくなるので。
以上。
![image](https://github.com/soja-suidou/shisetu_kanri_tenken/assets/139528738/6c06a93b-b179-4402-8247-b4fca14382a2)
